[project]
name = "vbg-guinee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dash>=4.0.0",
    "dotenv>=0.9.9",
    "flask-cors>=6.0.2",
    "nicegui>=3.7.1",
]
